---
language: ruby

script: "ruby lib/nethttputils.rb"

os:
  - linux
  - osx
rvm:
  - ruby-head
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0
  - jruby-head
matrix:
  allow_failures:
  # something with `NetHTTPUtils.request_data("http://localhost:8000/?1=2&3=4", form: {1=>3})` test
  - rvm: jruby-head
